FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OTPS=$JAVA_OPTS
#ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
COPY target/webapp-0.0.1-SNAPSHOT.jar webappdebug.jar
EXPOSE 8080
EXPOSE 5005
CMD [ "java", "-jar", "webappdebug.jar"]
